# This file is used by the Thunderstore CLI to build and publish to Thunderstore. https://github.com/thunderstore-io/thunderstore-cli

[config]
schemaVersion = "0.0.1"

[package]
namespace = "eia485"
name = "ExposePatchedMethods"
versionNumber = "4.0.2"
description = "exposes what mods you have loaded to your userspace or slots under your userRoot" # max 250 characters
websiteUrl = "http://github.com/EIA485/NeosExposePatchedMethods"
containsNsfwContent = false

[package.dependencies] 
ResoniteModding-BepisLoader = "1.4.0"

[build]
icon = "icon.png"
readme = "README.md"
outdir = "build"

# Copy the compiled DLL to the plugins folder in mod package
[[build.copy]]
source = "ExposePatchedMethods/bin/Release/net9.0/ExposePatchedMethods.dll"
target = "plugins/"

# Include PDB
[[build.copy]]
source = "ExposePatchedMethods/bin/Release/net9.0/ExposePatchedMethods.pdb"
target = "plugins/"

# include LICENSE file in mod package
[[build.copy]]
source = "license.txt"
target = "/"

[publish]
repository = "https://thunderstore.io"
communities = ["resonite"]

[publish.categories]
resonite = [ "mods", "misc" ] # https://thunderstore.io/api/experimental/community/resonite/category/